[AIO-15] Feature/Product 도메인 구성을 위한 초안
chaibin0/all-in-one pull request #11
Opened 2020-08-31 04:57 UTC by boring-km

commit message 참고바람

2020-08-31 11:14 UTC, chaibin0 commented on back-end/aio-core/product-core/build.gradle
> +	testCompileOnly('org.assertj:assertj-core:3.17.0')
assertJ는 Spring starter test에 이미 내장되어 있습니다.

2020-08-31 11:45 UTC, chaibin0 requested changes

2020-08-31 11:45 UTC, chaibin0 commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/ProductInfo.java
> +@Builder
@Data는
Getter, Setter, RequireArgsConstructor, ToString, EqualsAndHashCode가 합쳐져 있는데
쓰지 않는데 바람직하지 않음
@NoArgConstructor와 @Builder정도면 충분해 보임

2020-08-31 11:45 UTC, chaibin0 commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/ProductInfo.java
> +    @Setter private String address;
Field 기반의 @Setter는 좋지 않음
@Setter는 객체지향적으로 좋지 않기 때문에 왠만하면 지양해줬으면;

2020-08-31 11:45 UTC, chaibin0 commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/ProductInfo.java
> +
CreatedAt, CreatedBy, UpdatedAt, UpdatedBy 추가 바람

2020-08-31 11:45 UTC, chaibin0 commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/StatusType.java
> +    사용가능, 사용불가
한국어 type 쓰지 말것

2020-08-31 11:45 UTC, chaibin0 commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/ProductInfo.java
> +    @Setter private RentalPeriod rentalPeriod;
우리가 빌릴 수 있는 기간에서 중간중간 띄어질수도 있고 시간별로 나눠질수도 있을거같은데 start하고 end로 표현하기에는 너무 이상함

2020-08-31 11:45 UTC, chaibin0 commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/money/Won.java
> +
Web 프로그램에서는 Thread safe 하기 위해 불변클래스를 만드는 것보다 트랜잭션을 이용해서 구현을 함
그렇기 때문에 일반적인 클래스로 바꾸면 좋을거 같은데

2020-08-31 11:45 UTC, chaibin0 commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/price/PayTimeType.java
> +    PAY_PER_1_HOUR, PAY_PER_1_DAY
요일마다 가격이 전부 다르지 않을까?
성수기, 비수기일경우의 가격을 만들 수가 없을거같다.

2020-08-31 11:45 UTC, chaibin0 commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/space/RoomSize.java
> +    private int pyung;
평보다는 제곱미터만 사용함

2020-08-31 11:45 UTC, chaibin0 commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/space/RoomSize.java
> +    private int numberOfPeople;
Room 사이즈는 n~m명 이렇게 2개의 경우로 만들어 주자

2020-08-31 11:45 UTC, chaibin0 commented on back-end/aio-core/product-core/src/test/java/com/aio/allinone/vehicle/VehicleProductTest.java
> +                .isEqualTo(PricePolicy.builder()
isEqualTo에서 객체를 만드는건 좋지 않음 앞에 테스트 이전에 먼저 객체를 만들어 줄것

2020-08-31 11:46 UTC, chaibin0 approved these changes

2020-08-31 23:47 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/ProductInfo.java
> +    @Setter private String address;
@chaibin0 그리고 보니 어차피 DB화 할꺼면 수정을 굳이 코드 단계에서 안해도 되겠구나

2020-08-31 23:47 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/ProductInfo.java
> +@Builder
@NoArgConstructor랑 @builder 둘 다 써야함?
@builder만 쓰면 안되나

2020-08-31 23:50 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/ProductInfo.java
> +
@chaibin0 createdBy랑 updatedBy는 뭐임? 작성자?

2020-08-31 23:50 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/StatusType.java
> +    사용가능, 사용불가
쳇

2020-08-31 23:51 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/money/Won.java
> +
이건 나도 딱 정해서 하기가 애매함

2020-08-31 23:52 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/ProductInfo.java
> +    @Setter private RentalPeriod rentalPeriod;
빌릴 기간도 리스트로 만들어야 하나

2020-08-31 23:53 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/price/PayTimeType.java
> +    PAY_PER_1_HOUR, PAY_PER_1_DAY
그건 가격 정책에서 추가하자

2020-08-31 23:53 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/space/RoomSize.java
> +    private int pyung;
그럼 평 지운다

2020-08-31 23:54 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/space/RoomSize.java
> +    private int numberOfPeople;
ㅇㅋ

2020-08-31 23:54 UTC, boring-km commented on back-end/aio-core/product-core/src/test/java/com/aio/allinone/vehicle/VehicleProductTest.java
> +                .isEqualTo(PricePolicy.builder()
그렇게 바꿔봄

2020-09-01 00:06 UTC, boring-km commented on back-end/aio-core/product-core/build.gradle
> +	testCompileOnly('org.assertj:assertj-core:3.17.0')
몰랐음

2020-09-01 00:15 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/ProductInfo.java
> +@Builder
그래도 생성자는 있어야 한다는 건가

2020-09-01 00:17 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/ProductInfo.java
> +
작성자가 판매자 말고 있나

2020-09-01 00:25 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/price/PayTimeType.java
> +    PAY_PER_1_HOUR, PAY_PER_1_DAY
그리고 성수기, 비수기 개념을 넣어야함? @chaibin0

2020-09-01 00:43 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/ProductInfo.java
> +    @Setter private RentalPeriod rentalPeriod;
from to로 변경함

2020-09-01 00:45 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/money/Won.java
> +
@chaibin0 화폐 어떻게 해야하는 거냐 그래서 하~

2020-09-01 05:28 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/money/Won.java
> +
너가 좀 바꿔주래이

2020-09-01 05:30 UTC, boring-km commented on back-end/aio-core/product-core/src/main/java/com/aio/allinone/price/PayTimeType.java
> +    PAY_PER_1_HOUR, PAY_PER_1_DAY
그럼 요일마다 사용자가 일일이 다른 가격을 입력해야 한다는 얘기임?

2020-09-01 13:24 UTC, merged